../bin/checkhbond_Oacceptor -c 0.5 -m /acrm/usr/local/share/hb/data/hbmatrices.dat -n test/mcacc2.mat 1tsrB.pdb B280  B284 THR
../bin/checkhbond_Oacceptor -c 0.5 -m /acrm/usr/local/share/hb/data/hbmatrices.dat -n test/mcacc2.mat 1tsrB.pdb B118  B283 ARG
../bin/checkhbond_Oacceptor -c 0.5 -m /acrm/usr/local/share/hb/data/hbmatrices.dat -n test/mcacc2.mat 1tsrB.pdb B184  B183 SER
../bin/checkhbond_Oacceptor -c 0.5 -m /acrm/usr/local/share/hb/data/hbmatrices.dat -n test/mcacc2.mat 1tsrB.pdb B221  B230 THR
../bin/checkhbond_Oacceptor -c 0.5 -m /acrm/usr/local/share/hb/data/hbmatrices.dat -n test/mcacc2.mat 1tsrB.pdb B167  B170 THR
../bin/checkhbond_Oacceptor -c 0.5 -m /acrm/usr/local/share/hb/data/hbmatrices.dat -n test/mcacc2.mat 1tsrB.pdb B101  B267 ARG
../bin/checkhbond_Oacceptor -c 0.5 -m /acrm/usr/local/share/hb/data/hbmatrices.dat -n test/mcacc2.mat 1tsrB.pdb B101  B267 ARG
../bin/checkhbond_Oacceptor -c 0.5 -m /acrm/usr/local/share/hb/data/hbmatrices.dat -n test/mcacc2.mat 1tsrB.pdb B139  B235 ASN
../bin/checkhbond_Oacceptor -c 0.5 -m /acrm/usr/local/share/hb/data/hbmatrices.dat -n test/mcacc2.mat 1tsrB.pdb B107  B149 SER
../bin/checkhbond_Oacceptor -c 0.5 -m /acrm/usr/local/share/hb/data/hbmatrices.dat -n test/mcacc2.mat 1tsrB.pdb B189  B185 SER
../bin/checkhbond_Oacceptor -c 0.5 -m /acrm/usr/local/share/hb/data/hbmatrices.dat -n test/mcacc2.mat 1tsrB.pdb B124  B116 SER
../bin/checkhbond_Oacceptor -c 0.5 -m /acrm/usr/local/share/hb/data/hbmatrices.dat -n test/mcacc2.mat 1tsrB.pdb B108  B110 ARG
../bin/checkhbond_Oacceptor -c 0.5 -m /acrm/usr/local/share/hb/data/hbmatrices.dat -n test/mcacc2.mat 1tsrB.pdb B108  B110 ARG
../bin/checkhbond_Oacceptor -c 0.5 -m /acrm/usr/local/share/hb/data/hbmatrices.dat -n test/mcacc2.mat 1tsrB.pdb B117  B125 THR
../bin/checkhbond_Oacceptor -c 0.5 -m /acrm/usr/local/share/hb/data/hbmatrices.dat -n test/mcacc2.mat 1tsrB.pdb B245  B249 ARG
../bin/checkhbond_Oacceptor -c 0.5 -m /acrm/usr/local/share/hb/data/hbmatrices.dat -n test/mcacc2.mat 1tsrB.pdb B237  B175 ARG
../bin/checkhbond_Oacceptor -c 0.5 -m /acrm/usr/local/share/hb/data/hbmatrices.dat -n test/mcacc2.mat 1tsrB.pdb B237  B175 ARG
../bin/checkhbond_Oacceptor -c 0.5 -m /acrm/usr/local/share/hb/data/hbmatrices.dat -n test/mcacc2.mat 1tsrB.pdb B246  B249 ARG
../bin/checkhbond_Oacceptor -c 0.5 -m /acrm/usr/local/share/hb/data/hbmatrices.dat -n test/mcacc2.mat 1tsrB.pdb B274  B240 SER
../bin/checkhbond_Oacceptor -c 0.5 -m /acrm/usr/local/share/hb/data/hbmatrices.dat -n test/mcacc2.mat 1tsrB.pdb B152  B155 THR
../bin/checkhbond_Oacceptor -c 0.5 -m /acrm/usr/local/share/hb/data/hbmatrices.dat -n test/mcacc2.mat 1tsrB.pdb B191  B175 ARG
